server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb?serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show:
      sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: debug

